// Generated by `jadx-rs/tools/gen_dex_table.py` -- do not edit by hand.
//
// Source of truth: `jadx-plugins/jadx-dex-input/src/main/java/jadx/plugins/input/dex/insns/`
// (`DexOpcodes.java` for the numbers, `DexInsnMnemonics.java` for the names,
// `DexInsnInfo.java` + `DexInsnFormat.java` for the format, the register count
// and the index kind.)

/// Instruction format ids; the decoding of each format follows `DexInsnFormat`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
#[allow(non_camel_case_types)]
pub enum DexFmt {
	F_10T = 1,
	F_10X = 2,
	F_11N = 3,
	F_11X = 4,
	F_12X = 5,
	F_20T = 6,
	F_21C = 7,
	F_21H = 8,
	F_21S = 9,
	F_21T = 10,
	F_22B = 11,
	F_22C = 12,
	F_22S = 13,
	F_22T = 14,
	F_22X = 15,
	F_23X = 16,
	F_30T = 17,
	F_31C = 18,
	F_31I = 19,
	F_31T = 20,
	F_32X = 21,
	F_35C = 22,
	F_3RC = 23,
	F_45CC = 24,
	F_4RCC = 25,
	F_51I = 26,
}

impl DexFmt {
	/// length in 16-bit code units, including the opcode unit (jadx:
	/// `DexInsnFormat.UNITS`)
	pub fn units(self) -> u8 {
		match self {
			DexFmt::F_10T => 1,
			DexFmt::F_10X => 1,
			DexFmt::F_11N => 1,
			DexFmt::F_11X => 1,
			DexFmt::F_12X => 1,
			DexFmt::F_20T => 2,
			DexFmt::F_21C => 2,
			DexFmt::F_21H => 2,
			DexFmt::F_21S => 2,
			DexFmt::F_21T => 2,
			DexFmt::F_22B => 2,
			DexFmt::F_22C => 2,
			DexFmt::F_22S => 2,
			DexFmt::F_22T => 2,
			DexFmt::F_22X => 2,
			DexFmt::F_23X => 2,
			DexFmt::F_30T => 3,
			DexFmt::F_31C => 3,
			DexFmt::F_31I => 3,
			DexFmt::F_31T => 3,
			DexFmt::F_32X => 3,
			DexFmt::F_35C => 3,
			DexFmt::F_3RC => 3,
			DexFmt::F_45CC => 4,
			DexFmt::F_4RCC => 4,
			DexFmt::F_51I => 5,
		}
	}

	/// how many `v` registers the format names; `None` when the count is encoded
	/// in the instruction itself (jadx: `REG_COUNT == -1`)
	pub fn regs(self) -> Option<u8> {
		match self {
			DexFmt::F_10T => Some(0),
			DexFmt::F_10X => Some(0),
			DexFmt::F_11N => Some(1),
			DexFmt::F_11X => Some(1),
			DexFmt::F_12X => Some(2),
			DexFmt::F_20T => Some(0),
			DexFmt::F_21C => Some(1),
			DexFmt::F_21H => Some(1),
			DexFmt::F_21S => Some(1),
			DexFmt::F_21T => Some(1),
			DexFmt::F_22B => Some(2),
			DexFmt::F_22C => Some(2),
			DexFmt::F_22S => Some(2),
			DexFmt::F_22T => Some(2),
			DexFmt::F_22X => Some(2),
			DexFmt::F_23X => Some(3),
			DexFmt::F_30T => Some(0),
			DexFmt::F_31C => Some(1),
			DexFmt::F_31I => Some(1),
			DexFmt::F_31T => Some(1),
			DexFmt::F_32X => Some(2),
			DexFmt::F_35C => None,
			DexFmt::F_3RC => None,
			DexFmt::F_45CC => None,
			DexFmt::F_4RCC => None,
			DexFmt::F_51I => Some(1),
		}
	}

	/// `true` for the call formats, whose register count is part of the
	/// instruction (`35c`, `3rc`, `45cc`, `4rcc`)
	pub fn is_variadic(self) -> bool {
		self.regs().is_none()
	}
}

/// Which index table the index operand of an instruction points into
/// (jadx: `InsnIndexType`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum IdxKind {
	None = 0,
	String = 1,
	Type = 2,
	Field = 3,
	Method = 4,
	CallSite = 5,
}

/// One opcode: mnemonic, format and index kind (jadx: `DexInsnInfo`).
#[derive(Debug, Clone, Copy)]
pub struct DexOpInfo {
	pub name: &'static str,
	pub fmt: DexFmt,
	pub idx: IdxKind,
}

/// `DexInsnInfo.INSN_INFO`: one entry per opcode byte. Opcodes jadx leaves
/// unregistered keep the mnemonic from `DexInsnMnemonics` (`"unused"`) and the
/// shortest format, so a listing shows the raw unit instead of stopping.
pub static DEX_OPS: [DexOpInfo; 256] = [
	DexOpInfo { name: "nop", fmt: DexFmt::F_10X, idx: IdxKind::None },
	DexOpInfo { name: "move", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "move/from16", fmt: DexFmt::F_22X, idx: IdxKind::None },
	DexOpInfo { name: "move/16", fmt: DexFmt::F_32X, idx: IdxKind::None },
	DexOpInfo { name: "move-wide", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "move-wide/from16", fmt: DexFmt::F_22X, idx: IdxKind::None },
	DexOpInfo { name: "move-wide/16", fmt: DexFmt::F_32X, idx: IdxKind::None },
	DexOpInfo { name: "move-object", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "move-object/from16", fmt: DexFmt::F_22X, idx: IdxKind::None },
	DexOpInfo { name: "move-object/16", fmt: DexFmt::F_32X, idx: IdxKind::None },
	DexOpInfo { name: "move-result", fmt: DexFmt::F_11X, idx: IdxKind::None },
	DexOpInfo { name: "move-result-wide", fmt: DexFmt::F_11X, idx: IdxKind::None },
	DexOpInfo { name: "move-result-object", fmt: DexFmt::F_11X, idx: IdxKind::None },
	DexOpInfo { name: "move-exception", fmt: DexFmt::F_11X, idx: IdxKind::None },
	DexOpInfo { name: "return-void", fmt: DexFmt::F_10X, idx: IdxKind::None },
	DexOpInfo { name: "return", fmt: DexFmt::F_11X, idx: IdxKind::None },
	DexOpInfo { name: "return-wide", fmt: DexFmt::F_11X, idx: IdxKind::None },
	DexOpInfo { name: "return-object", fmt: DexFmt::F_11X, idx: IdxKind::None },
	DexOpInfo { name: "const/4", fmt: DexFmt::F_11N, idx: IdxKind::None },
	DexOpInfo { name: "const/16", fmt: DexFmt::F_21S, idx: IdxKind::None },
	DexOpInfo { name: "const", fmt: DexFmt::F_31I, idx: IdxKind::None },
	DexOpInfo { name: "const/high16", fmt: DexFmt::F_21H, idx: IdxKind::None },
	DexOpInfo { name: "const-wide/16", fmt: DexFmt::F_21S, idx: IdxKind::None },
	DexOpInfo { name: "const-wide/32", fmt: DexFmt::F_31I, idx: IdxKind::None },
	DexOpInfo { name: "const-wide", fmt: DexFmt::F_51I, idx: IdxKind::None },
	DexOpInfo { name: "const-wide/high16", fmt: DexFmt::F_21H, idx: IdxKind::None },
	DexOpInfo { name: "const-string", fmt: DexFmt::F_21C, idx: IdxKind::String },
	DexOpInfo { name: "const-string/jumbo", fmt: DexFmt::F_31C, idx: IdxKind::String },
	DexOpInfo { name: "const-class", fmt: DexFmt::F_21C, idx: IdxKind::Type },
	DexOpInfo { name: "monitor-enter", fmt: DexFmt::F_11X, idx: IdxKind::None },
	DexOpInfo { name: "monitor-exit", fmt: DexFmt::F_11X, idx: IdxKind::None },
	DexOpInfo { name: "check-cast", fmt: DexFmt::F_21C, idx: IdxKind::Type },
	DexOpInfo { name: "instance-of", fmt: DexFmt::F_22C, idx: IdxKind::Type },
	DexOpInfo { name: "array-length", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "new-instance", fmt: DexFmt::F_21C, idx: IdxKind::Type },
	DexOpInfo { name: "new-array", fmt: DexFmt::F_22C, idx: IdxKind::Type },
	DexOpInfo { name: "filled-new-array", fmt: DexFmt::F_35C, idx: IdxKind::Type },
	DexOpInfo { name: "filled-new-array/range", fmt: DexFmt::F_3RC, idx: IdxKind::Type },
	DexOpInfo { name: "fill-array-data", fmt: DexFmt::F_31T, idx: IdxKind::None },
	DexOpInfo { name: "throw", fmt: DexFmt::F_11X, idx: IdxKind::None },
	DexOpInfo { name: "goto", fmt: DexFmt::F_10T, idx: IdxKind::None },
	DexOpInfo { name: "goto/16", fmt: DexFmt::F_20T, idx: IdxKind::None },
	DexOpInfo { name: "goto/32", fmt: DexFmt::F_30T, idx: IdxKind::None },
	DexOpInfo { name: "packed-switch", fmt: DexFmt::F_31T, idx: IdxKind::None },
	DexOpInfo { name: "sparse-switch", fmt: DexFmt::F_31T, idx: IdxKind::None },
	DexOpInfo { name: "cmpl-float", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "cmpg-float", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "cmpl-double", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "cmpg-double", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "cmp-long", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "if-eq", fmt: DexFmt::F_22T, idx: IdxKind::None },
	DexOpInfo { name: "if-ne", fmt: DexFmt::F_22T, idx: IdxKind::None },
	DexOpInfo { name: "if-lt", fmt: DexFmt::F_22T, idx: IdxKind::None },
	DexOpInfo { name: "if-ge", fmt: DexFmt::F_22T, idx: IdxKind::None },
	DexOpInfo { name: "if-gt", fmt: DexFmt::F_22T, idx: IdxKind::None },
	DexOpInfo { name: "if-le", fmt: DexFmt::F_22T, idx: IdxKind::None },
	DexOpInfo { name: "if-eqz", fmt: DexFmt::F_21T, idx: IdxKind::None },
	DexOpInfo { name: "if-nez", fmt: DexFmt::F_21T, idx: IdxKind::None },
	DexOpInfo { name: "if-ltz", fmt: DexFmt::F_21T, idx: IdxKind::None },
	DexOpInfo { name: "if-gez", fmt: DexFmt::F_21T, idx: IdxKind::None },
	DexOpInfo { name: "if-gtz", fmt: DexFmt::F_21T, idx: IdxKind::None },
	DexOpInfo { name: "if-lez", fmt: DexFmt::F_21T, idx: IdxKind::None },
	DexOpInfo { name: "(unused)", fmt: DexFmt::F_10T, idx: IdxKind::None }, // jadx: not registered
	DexOpInfo { name: "(unused)", fmt: DexFmt::F_10T, idx: IdxKind::None }, // jadx: not registered
	DexOpInfo { name: "(unused)", fmt: DexFmt::F_10T, idx: IdxKind::None }, // jadx: not registered
	DexOpInfo { name: "(unused)", fmt: DexFmt::F_10T, idx: IdxKind::None }, // jadx: not registered
	DexOpInfo { name: "(unused)", fmt: DexFmt::F_10T, idx: IdxKind::None }, // jadx: not registered
	DexOpInfo { name: "(unused)", fmt: DexFmt::F_10T, idx: IdxKind::None }, // jadx: not registered
	DexOpInfo { name: "aget", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "aget-wide", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "aget-object", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "aget-boolean", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "aget-byte", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "aget-char", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "aget-short", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "aput", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "aput-wide", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "aput-object", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "aput-boolean", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "aput-byte", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "aput-char", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "aput-short", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "iget", fmt: DexFmt::F_22C, idx: IdxKind::Field },
	DexOpInfo { name: "iget-wide", fmt: DexFmt::F_22C, idx: IdxKind::Field },
	DexOpInfo { name: "iget-object", fmt: DexFmt::F_22C, idx: IdxKind::Field },
	DexOpInfo { name: "iget-boolean", fmt: DexFmt::F_22C, idx: IdxKind::Field },
	DexOpInfo { name: "iget-byte", fmt: DexFmt::F_22C, idx: IdxKind::Field },
	DexOpInfo { name: "iget-char", fmt: DexFmt::F_22C, idx: IdxKind::Field },
	DexOpInfo { name: "iget-short", fmt: DexFmt::F_22C, idx: IdxKind::Field },
	DexOpInfo { name: "iput", fmt: DexFmt::F_22C, idx: IdxKind::Field },
	DexOpInfo { name: "iput-wide", fmt: DexFmt::F_22C, idx: IdxKind::Field },
	DexOpInfo { name: "iput-object", fmt: DexFmt::F_22C, idx: IdxKind::Field },
	DexOpInfo { name: "iput-boolean", fmt: DexFmt::F_22C, idx: IdxKind::Field },
	DexOpInfo { name: "iput-byte", fmt: DexFmt::F_22C, idx: IdxKind::Field },
	DexOpInfo { name: "iput-char", fmt: DexFmt::F_22C, idx: IdxKind::Field },
	DexOpInfo { name: "iput-short", fmt: DexFmt::F_22C, idx: IdxKind::Field },
	DexOpInfo { name: "sget", fmt: DexFmt::F_21C, idx: IdxKind::Field },
	DexOpInfo { name: "sget-wide", fmt: DexFmt::F_21C, idx: IdxKind::Field },
	DexOpInfo { name: "sget-object", fmt: DexFmt::F_21C, idx: IdxKind::Field },
	DexOpInfo { name: "sget-boolean", fmt: DexFmt::F_21C, idx: IdxKind::Field },
	DexOpInfo { name: "sget-byte", fmt: DexFmt::F_21C, idx: IdxKind::Field },
	DexOpInfo { name: "sget-char", fmt: DexFmt::F_21C, idx: IdxKind::Field },
	DexOpInfo { name: "sget-short", fmt: DexFmt::F_21C, idx: IdxKind::Field },
	DexOpInfo { name: "sput", fmt: DexFmt::F_21C, idx: IdxKind::Field },
	DexOpInfo { name: "sput-wide", fmt: DexFmt::F_21C, idx: IdxKind::Field },
	DexOpInfo { name: "sput-object", fmt: DexFmt::F_21C, idx: IdxKind::Field },
	DexOpInfo { name: "sput-boolean", fmt: DexFmt::F_21C, idx: IdxKind::Field },
	DexOpInfo { name: "sput-byte", fmt: DexFmt::F_21C, idx: IdxKind::Field },
	DexOpInfo { name: "sput-char", fmt: DexFmt::F_21C, idx: IdxKind::Field },
	DexOpInfo { name: "sput-short", fmt: DexFmt::F_21C, idx: IdxKind::Field },
	DexOpInfo { name: "invoke-virtual", fmt: DexFmt::F_35C, idx: IdxKind::Method },
	DexOpInfo { name: "invoke-super", fmt: DexFmt::F_35C, idx: IdxKind::Method },
	DexOpInfo { name: "invoke-direct", fmt: DexFmt::F_35C, idx: IdxKind::Method },
	DexOpInfo { name: "invoke-static", fmt: DexFmt::F_35C, idx: IdxKind::Method },
	DexOpInfo { name: "invoke-interface", fmt: DexFmt::F_35C, idx: IdxKind::Method },
	DexOpInfo { name: "(unused)", fmt: DexFmt::F_10T, idx: IdxKind::None }, // jadx: not registered
	DexOpInfo { name: "invoke-virtual/range", fmt: DexFmt::F_3RC, idx: IdxKind::Method },
	DexOpInfo { name: "invoke-super/range", fmt: DexFmt::F_3RC, idx: IdxKind::Method },
	DexOpInfo { name: "invoke-direct/range", fmt: DexFmt::F_3RC, idx: IdxKind::Method },
	DexOpInfo { name: "invoke-static/range", fmt: DexFmt::F_3RC, idx: IdxKind::Method },
	DexOpInfo { name: "invoke-interface/range", fmt: DexFmt::F_3RC, idx: IdxKind::Method },
	DexOpInfo { name: "(unused)", fmt: DexFmt::F_10T, idx: IdxKind::None }, // jadx: not registered
	DexOpInfo { name: "(unused)", fmt: DexFmt::F_10T, idx: IdxKind::None }, // jadx: not registered
	DexOpInfo { name: "neg-int", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "not-int", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "neg-long", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "not-long", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "neg-float", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "neg-double", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "int-to-long", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "int-to-float", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "int-to-double", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "long-to-int", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "long-to-float", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "long-to-double", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "float-to-int", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "float-to-long", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "float-to-double", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "double-to-int", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "double-to-long", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "double-to-float", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "int-to-byte", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "int-to-char", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "int-to-short", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "add-int", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "sub-int", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "mul-int", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "div-int", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "rem-int", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "and-int", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "or-int", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "xor-int", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "shl-int", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "shr-int", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "ushr-int", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "add-long", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "sub-long", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "mul-long", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "div-long", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "rem-long", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "and-long", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "or-long", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "xor-long", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "shl-long", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "shr-long", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "ushr-long", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "add-float", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "sub-float", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "mul-float", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "div-float", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "rem-float", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "add-double", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "sub-double", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "mul-double", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "div-double", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "rem-double", fmt: DexFmt::F_23X, idx: IdxKind::None },
	DexOpInfo { name: "add-int/2addr", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "sub-int/2addr", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "mul-int/2addr", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "div-int/2addr", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "rem-int/2addr", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "and-int/2addr", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "or-int/2addr", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "xor-int/2addr", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "shl-int/2addr", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "shr-int/2addr", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "ushr-int/2addr", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "add-long/2addr", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "sub-long/2addr", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "mul-long/2addr", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "div-long/2addr", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "rem-long/2addr", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "and-long/2addr", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "or-long/2addr", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "xor-long/2addr", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "shl-long/2addr", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "shr-long/2addr", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "ushr-long/2addr", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "add-float/2addr", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "sub-float/2addr", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "mul-float/2addr", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "div-float/2addr", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "rem-float/2addr", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "add-double/2addr", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "sub-double/2addr", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "mul-double/2addr", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "div-double/2addr", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "rem-double/2addr", fmt: DexFmt::F_12X, idx: IdxKind::None },
	DexOpInfo { name: "add-int/lit16", fmt: DexFmt::F_22S, idx: IdxKind::None },
	DexOpInfo { name: "rsub-int", fmt: DexFmt::F_22S, idx: IdxKind::None },
	DexOpInfo { name: "mul-int/lit16", fmt: DexFmt::F_22S, idx: IdxKind::None },
	DexOpInfo { name: "div-int/lit16", fmt: DexFmt::F_22S, idx: IdxKind::None },
	DexOpInfo { name: "rem-int/lit16", fmt: DexFmt::F_22S, idx: IdxKind::None },
	DexOpInfo { name: "and-int/lit16", fmt: DexFmt::F_22S, idx: IdxKind::None },
	DexOpInfo { name: "or-int/lit16", fmt: DexFmt::F_22S, idx: IdxKind::None },
	DexOpInfo { name: "xor-int/lit16", fmt: DexFmt::F_22S, idx: IdxKind::None },
	DexOpInfo { name: "add-int/lit8", fmt: DexFmt::F_22B, idx: IdxKind::None },
	DexOpInfo { name: "rsub-int/lit8", fmt: DexFmt::F_22B, idx: IdxKind::None },
	DexOpInfo { name: "mul-int/lit8", fmt: DexFmt::F_22B, idx: IdxKind::None },
	DexOpInfo { name: "div-int/lit8", fmt: DexFmt::F_22B, idx: IdxKind::None },
	DexOpInfo { name: "rem-int/lit8", fmt: DexFmt::F_22B, idx: IdxKind::None },
	DexOpInfo { name: "and-int/lit8", fmt: DexFmt::F_22B, idx: IdxKind::None },
	DexOpInfo { name: "or-int/lit8", fmt: DexFmt::F_22B, idx: IdxKind::None },
	DexOpInfo { name: "xor-int/lit8", fmt: DexFmt::F_22B, idx: IdxKind::None },
	DexOpInfo { name: "shl-int/lit8", fmt: DexFmt::F_22B, idx: IdxKind::None },
	DexOpInfo { name: "shr-int/lit8", fmt: DexFmt::F_22B, idx: IdxKind::None },
	DexOpInfo { name: "ushr-int/lit8", fmt: DexFmt::F_22B, idx: IdxKind::None },
	DexOpInfo { name: "(unused)", fmt: DexFmt::F_10T, idx: IdxKind::None }, // jadx: not registered
	DexOpInfo { name: "(unused)", fmt: DexFmt::F_10T, idx: IdxKind::None }, // jadx: not registered
	DexOpInfo { name: "(unused)", fmt: DexFmt::F_10T, idx: IdxKind::None }, // jadx: not registered
	DexOpInfo { name: "(unused)", fmt: DexFmt::F_10T, idx: IdxKind::None }, // jadx: not registered
	DexOpInfo { name: "(unused)", fmt: DexFmt::F_10T, idx: IdxKind::None }, // jadx: not registered
	DexOpInfo { name: "(unused)", fmt: DexFmt::F_10T, idx: IdxKind::None }, // jadx: not registered
	DexOpInfo { name: "(unused)", fmt: DexFmt::F_10T, idx: IdxKind::None }, // jadx: not registered
	DexOpInfo { name: "(unused)", fmt: DexFmt::F_10T, idx: IdxKind::None }, // jadx: not registered
	DexOpInfo { name: "(unused)", fmt: DexFmt::F_10T, idx: IdxKind::None }, // jadx: not registered
	DexOpInfo { name: "(unused)", fmt: DexFmt::F_10T, idx: IdxKind::None }, // jadx: not registered
	DexOpInfo { name: "(unused)", fmt: DexFmt::F_10T, idx: IdxKind::None }, // jadx: not registered
	DexOpInfo { name: "(unused)", fmt: DexFmt::F_10T, idx: IdxKind::None }, // jadx: not registered
	DexOpInfo { name: "(unused)", fmt: DexFmt::F_10T, idx: IdxKind::None }, // jadx: not registered
	DexOpInfo { name: "(unused)", fmt: DexFmt::F_10T, idx: IdxKind::None }, // jadx: not registered
	DexOpInfo { name: "(unused)", fmt: DexFmt::F_10T, idx: IdxKind::None }, // jadx: not registered
	DexOpInfo { name: "(unused)", fmt: DexFmt::F_10T, idx: IdxKind::None }, // jadx: not registered
	DexOpInfo { name: "(unused)", fmt: DexFmt::F_10T, idx: IdxKind::None }, // jadx: not registered
	DexOpInfo { name: "(unused)", fmt: DexFmt::F_10T, idx: IdxKind::None }, // jadx: not registered
	DexOpInfo { name: "(unused)", fmt: DexFmt::F_10T, idx: IdxKind::None }, // jadx: not registered
	DexOpInfo { name: "(unused)", fmt: DexFmt::F_10T, idx: IdxKind::None }, // jadx: not registered
	DexOpInfo { name: "(unused)", fmt: DexFmt::F_10T, idx: IdxKind::None }, // jadx: not registered
	DexOpInfo { name: "(unused)", fmt: DexFmt::F_10T, idx: IdxKind::None }, // jadx: not registered
	DexOpInfo { name: "(unused)", fmt: DexFmt::F_10T, idx: IdxKind::None }, // jadx: not registered
	DexOpInfo { name: "invoke-polymorphic", fmt: DexFmt::F_45CC, idx: IdxKind::Method },
	DexOpInfo { name: "invoke-polymorphic/range", fmt: DexFmt::F_4RCC, idx: IdxKind::Method },
	DexOpInfo { name: "invoke-custom", fmt: DexFmt::F_35C, idx: IdxKind::CallSite },
	DexOpInfo { name: "invoke-custom/range", fmt: DexFmt::F_3RC, idx: IdxKind::CallSite },
	DexOpInfo { name: "const-method-handle", fmt: DexFmt::F_21C, idx: IdxKind::None },
	DexOpInfo { name: "const-method-type", fmt: DexFmt::F_21C, idx: IdxKind::None },
];

/// Payload pseudo-opcodes: `nop` is followed by one of these ident units (jadx:
/// `DexInsnInfo.PAYLOAD_INFO`, dex format 6.2.23).
pub const PAYLOAD_PACKED_SWITCH: u16 = 0x0100;
pub const PAYLOAD_SPARSE_SWITCH: u16 = 0x0200;
pub const PAYLOAD_FILL_ARRAY_DATA: u16 = 0x0300;

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn table_matches_the_upstream_tables() {
		assert_eq!(DEX_OPS.len(), 256);
		assert_eq!(DEX_OPS[0x00].name, "nop");
		assert_eq!(DEX_OPS[0x01].name, "move");
		assert_eq!(DEX_OPS[0x01].fmt.units(), 1);
		assert_eq!(DEX_OPS[0x01].fmt.regs(), Some(2));
		assert_eq!(DEX_OPS[0x28].name, "goto");
		assert_eq!(DEX_OPS[0x28].fmt.units(), 1);
		assert_eq!(DEX_OPS[0x1a].name, "const-string");
		assert_eq!(DEX_OPS[0x1a].idx, IdxKind::String);
		assert_eq!(DEX_OPS[0x18].fmt.units(), 6);
		assert_eq!(DEX_OPS[0x6e].name, "invoke-virtual");
		assert!(DEX_OPS[0x6e].fmt.is_variadic());
		assert_eq!(DEX_OPS[0x6e].fmt.units(), 3);
		assert_eq!(DEX_OPS[0x2b].name, "packed-switch");
		assert_eq!(DEX_OPS[0x2b].fmt, DexFmt::F_31T);
	}

	#[test]
	fn payload_ids_match_the_spec() {
		assert_eq!(PAYLOAD_PACKED_SWITCH, 0x0100);
		assert_eq!(PAYLOAD_SPARSE_SWITCH, 0x0200);
		assert_eq!(PAYLOAD_FILL_ARRAY_DATA, 0x0300);
	}
}
