#!/usr/bin/env python3
"""Regenerate `crates/jadx-rs/src/dex/table.rs` from jadx's own DEX tables.

Run from the repository root:

    python3 jadx-rs/tools/gen_dex_table.py [path-to-jadx-tree]

The java files this reads are the upstream source of truth:
`DexOpcodes.java` (opcode numbers), `DexInsnMnemonics.java` (mnemonics),
`DexInsnInfo.java` + `DexInsnFormat.java` (format, register count, index kind).
Generating the Rust table from them keeps this port's DEX disassembler
opcode-for-opcode identical to jadx's -- and it removes any need to remember
whether `goto` is 0x20 or 0x28 (it is 0x28 in the current dex spec).
"""
import re
import sys
from pathlib import Path

root = Path(sys.argv[1] if len(sys.argv) > 1 else ".").resolve()
base = root / "jadx-plugins/jadx-dex-input/src/main/java/jadx/plugins/input/dex/insns"
if not base.is_dir():
    sys.exit("jadx source tree not found: " + str(base))
out_dir = root / "jadx-rs/crates/jadx-rs/src/dex"
out_dir.mkdir(parents=True, exist_ok=True)

opcodes = {}
for line in (base / "DexOpcodes.java").read_text().splitlines():
    m = re.search(r"int\s+([A-Z0-9_]+)\s*=\s*(0x[0-9a-fA-F]+|\d+)\s*;", line)
    if m:
        opcodes[m.group(1)] = int(m.group(2), 0)

mnem_src = (base / "DexInsnMnemonics.java").read_text()
mnem = re.findall(r'"([^"]*)"', mnem_src.split("MNEMONICS = new String[] {")[1].split("};")[0])

ftxt = (base / "DexInsnFormat.java").read_text()
fmt = {}
for m in re.finditer(r"FORMAT_([A-Z0-9]+)\s*=\s*new DexInsnFormat\((-?\d+),\s*(-?\d+)\)", ftxt):
    fmt[m.group(1)] = (int(m.group(2)), int(m.group(3)))
for m in re.finditer(r"FORMAT_([A-Z0-9]+)\s*=\s*FORMAT_([A-Z0-9]+);", ftxt):
    if m.group(2) in fmt:
        fmt[m.group(1)] = fmt[m.group(2)]

itxt = (base / "DexInsnInfo.java").read_text()
pat = re.compile(
    r"register\(arr,\s*DexOpcodes\.([A-Z0-9_]+),\s*Opcode\.([A-Z0-9_]+),\s*"
    r"DexInsnFormat\.FORMAT_([A-Z0-9]+)(?:,\s*InsnIndexType\.([A-Z_]+))?\)"
)
rows = {}
for m in pat.finditer(itxt):
    name, f, idx = m.group(1), m.group(3), m.group(4) or ""
    if name not in opcodes:
        sys.exit("unknown opcode constant: " + name)
    if f not in fmt:
        sys.exit("unknown format: " + f)
    rows[opcodes[name]] = (f, idx)

# only formats that are actually referenced, so the enum does not grow with the
# aliases jadx never registers (`35ms`, `22cs`, ...)
used = sorted({name for (name, _idx) in rows.values()}, key=lambda x: (fmt[x][0], x))
fid = {f: i + 1 for i, f in enumerate(used)}

IDX_NAME = {
	"": "None",
	"NONE": "None",
	"STRING_REF": "String",
	"TYPE_REF": "Type",
	"FIELD_REF": "Field",
	"METHOD_REF": "Method",
	"CALL_SITE": "CallSite",
}

L = []


def w(s=""):
    L.append(s)


w("// Generated by `jadx-rs/tools/gen_dex_table.py` -- do not edit by hand.")
w("//")
w("// Source of truth: `jadx-plugins/jadx-dex-input/src/main/java/jadx/plugins/input/dex/insns/`")
w("// (`DexOpcodes.java` for the numbers, `DexInsnMnemonics.java` for the names,")
w("// `DexInsnInfo.java` + `DexInsnFormat.java` for the format, the register count")
w("// and the index kind.)")
w()
w("/// Instruction format ids; the decoding of each format follows `DexInsnFormat`.")
w("#[derive(Debug, Clone, Copy, PartialEq, Eq)]")
w("#[repr(u8)]")
w("#[allow(non_camel_case_types)]")
w("pub enum DexFmt {")
for f in used:
    w("\tF_%s = %d," % (f, fid[f]))
w("}")
w()
w("impl DexFmt {")
w("\t/// length in 16-bit code units, including the opcode unit (jadx:")
w("\t/// `DexInsnFormat.UNITS`)")
w("\tpub fn units(self) -> u8 {")
w("\t\tmatch self {")
for f in used:
    w("\t\t\tDexFmt::F_%s => %d," % (f, fmt[f][0]))
w("\t\t}")
w("\t}")
w()
w("\t/// how many `v` registers the format names; `None` when the count is encoded")
w("\t/// in the instruction itself (jadx: `REG_COUNT == -1`)")
w("\tpub fn regs(self) -> Option<u8> {")
w("\t\tmatch self {")
for f in used:
    n = fmt[f][1]
    w("\t\t\tDexFmt::F_%s => %s," % (f, "None" if n < 0 else "Some(%d)" % n))
w("\t\t}")
w("\t}")
w()
w("\t/// `true` for the call formats, whose register count is part of the")
w("\t/// instruction (`35c`, `3rc`, `45cc`, `4rcc`)")
w("\tpub fn is_variadic(self) -> bool {")
w("\t\tself.regs().is_none()")
w("\t}")
w("}")
w()
w("/// Which index table the index operand of an instruction points into")
w("/// (jadx: `InsnIndexType`).")
w("#[derive(Debug, Clone, Copy, PartialEq, Eq)]")
w("#[repr(u8)]")
w("pub enum IdxKind {")
w("\tNone = 0,")
w("\tString = 1,")
w("\tType = 2,")
w("\tField = 3,")
w("\tMethod = 4,")
w("\tCallSite = 5,")
w("}")
w()
w("/// One opcode: mnemonic, format and index kind (jadx: `DexInsnInfo`).")
w("#[derive(Debug, Clone, Copy)]")
w("pub struct DexOpInfo {")
w("\tpub name: &'static str,")
w("\tpub fmt: DexFmt,")
w("\tpub idx: IdxKind,")
w("}")
w()
w("/// `DexInsnInfo.INSN_INFO`: one entry per opcode byte. Opcodes jadx leaves")
w("/// unregistered keep the mnemonic from `DexInsnMnemonics` (`\"unused\"`) and the")
w("/// shortest format, so a listing shows the raw unit instead of stopping.")
w("pub static DEX_OPS: [DexOpInfo; 256] = [")
for op in range(256):
    nm = mnem[op] if op < len(mnem) else "unused"
    if op in rows:
        f, i = rows[op]
        w('\tDexOpInfo { name: "%s", fmt: DexFmt::F_%s, idx: IdxKind::%s },' % (nm, f, IDX_NAME[i]))
    else:
        w('\tDexOpInfo { name: "%s", fmt: DexFmt::F_%s, idx: IdxKind::None }, // jadx: not registered' % (nm, used[0]))
w("];")
w()
w("/// Payload pseudo-opcodes: `nop` is followed by one of these ident units (jadx:")
w("/// `DexInsnInfo.PAYLOAD_INFO`, dex format 6.2.23).")
w("pub const PAYLOAD_PACKED_SWITCH: u16 = 0x0100;")
w("pub const PAYLOAD_SPARSE_SWITCH: u16 = 0x0200;")
w("pub const PAYLOAD_FILL_ARRAY_DATA: u16 = 0x0300;")
w()
w("#[cfg(test)]")
w("mod tests {")
w("\tuse super::*;")
w()
w("\t#[test]")
w("\tfn table_matches_the_upstream_tables() {")
w("\t\tassert_eq!(DEX_OPS.len(), 256);")
w('\t\tassert_eq!(DEX_OPS[0x00].name, "nop");')
w('\t\tassert_eq!(DEX_OPS[0x01].name, "move");')
w("\t\tassert_eq!(DEX_OPS[0x01].fmt.units(), 1);")
w("\t\tassert_eq!(DEX_OPS[0x01].fmt.regs(), Some(2));")
w("\t\tassert_eq!(DEX_OPS[0x28].name, \"goto\");")
w("\t\tassert_eq!(DEX_OPS[0x28].fmt.units(), 1);")
w("\t\tassert_eq!(DEX_OPS[0x1a].name, \"const-string\");")
w("\t\tassert_eq!(DEX_OPS[0x1a].idx, IdxKind::String);")
w("\t\tassert_eq!(DEX_OPS[0x18].fmt.units(), 6);")
w("\t\tassert_eq!(DEX_OPS[0x6e].name, \"invoke-virtual\");")
w("\t\tassert!(DEX_OPS[0x6e].fmt.is_variadic());")
w("\t\tassert_eq!(DEX_OPS[0x6e].fmt.units(), 3);")
w("\t\tassert_eq!(DEX_OPS[0x2b].name, \"packed-switch\");")
w("\t\tassert_eq!(DEX_OPS[0x2b].fmt, DexFmt::F_31T);")
w("\t}")
w()
w("\t#[test]")
w("\tfn payload_ids_match_the_spec() {")
w("\t\tassert_eq!(PAYLOAD_PACKED_SWITCH, 0x0100);")
w("\t\tassert_eq!(PAYLOAD_SPARSE_SWITCH, 0x0200);")
w("\t\tassert_eq!(PAYLOAD_FILL_ARRAY_DATA, 0x0300);")
w("\t}")
w("}")
w()

(out_dir / "table.rs").write_text("\n".join(L))
print("wrote %s: %d lines, %d registered opcodes, %d formats" % (out_dir / "table.rs", len(L), len(rows), len(used)))
