//! Deobfuscation name generation -- port of `jadx.core.deobf.DeobfAliasProvider`
//! plus `jadx.core.deobf.NameMapper`.
//!
//! jadx renames only the members selected by the `deobfMinLen`/whitelist
//! conditions (`deobf/conditions/*`, not ported; see `docs/PORT_STATUS.md`), and
//! the replacement names are generated by `DeobfAliasProvider`:
//!
//! | kind    | jadx format          | example       |
//! |---------|----------------------|---------------|
//! | package | `p%03d%s`            | `p001a`       |
//! | class   | `{prefix}C%04d%s`    | `AbstractC0002a` |
//! | field   | `f%d%s`             | `f12x`        |
//! | method  | `m%d%s` / `mo%d%s`  | `m3a`         |
//!
//! The trailing `%s` is `prepareNamePart(orig)`: when the original name is longer
//! than `deobfMaxLength` (jadx default 12) it becomes `'x' + hex(Java hashCode)`,
//! otherwise the invalid characters are simply removed. Reproducing that exactly
//! matters: the `.jobf` mapping file is meant to stay stable across runs and
//! across the Java and Rust implementations.

use crate::access_flags;

/// Java's `String.hashCode` (JLS 3.10.7, `String.hashCode` javadoc):
/// `s[0]*31^(n-1) + ... + s[n-1]` in 32-bit two's complement. Java allows the
/// overflow; Rust wraps in release and panics in debug, so `wrapping_*` is needed
/// to get bit-identical results.
pub fn java_hash_code(s: &str) -> i32 {
	let mut h: i32 = 0;
	for c in s.chars() {
		// Java iterates UTF-16 code units, not unicode scalars
		for u in c.encode_utf16() {
			h = h
				.wrapping_mul(31)
				.wrapping_add(i32::from(u));
		}
	}
	h
}

/// jadx: `NameMapper.isPrintableAsciiCodePoint` + `isValidIdentifierPart`.
pub fn is_identifier_part(c: char) -> bool {
	if c.is_ascii_alphanumeric() || c == '_' || c == '$' {
		return true;
	}
	// Java's `\p{javaJavaIdentifierPart}` also accepts unicode letters and digits;
	// `char::is_alphanumeric` is the closest `core` equivalent.
	(c as u32) > 127 && (c.is_alphabetic() || c.is_numeric())
}

/// jadx: `NameMapper.isIdentifierStart`.
pub fn is_identifier_start(c: char) -> bool {
	if c.is_ascii_alphabetic() || c == '_' || c == '$' {
		return true;
	}
	(c as u32) > 127 && c.is_alphabetic()
}

/// jadx: `NameMapper.removeInvalidCharsMiddle` -- keep only printable ASCII
/// identifier characters.
pub fn remove_invalid_chars_middle(name: &str) -> String {
	if is_valid_identifier(name) {
		return name.to_string();
	}
	name.chars().filter(|c| is_identifier_part(*c)).collect()
}

/// jadx: `NameMapper.RESERVED_NAMES` (the identifiers a rename may never produce).
pub const RESERVED_NAMES: &[&str] = &[
	"abstract", "assert", "boolean", "break", "byte", "case", "catch", "char", "class", "const",
	"continue", "default", "do", "double", "else", "enum", "extends", "false", "final", "finally",
	"float", "for", "goto", "if", "implements", "import", "instanceof", "int", "interface",
	"long", "native", "new", "null", "package", "private", "protected", "public", "return",
	"short", "static", "strictfp", "super", "switch", "synchronized", "this", "throw", "throws",
	"transient", "true", "try", "void", "volatile", "while", "_",
];

pub fn is_reserved(s: &str) -> bool {
	RESERVED_NAMES.contains(&s)
}

/// jadx: `NameMapper.isValidIdentifier`.
pub fn is_valid_identifier(s: &str) -> bool {
	!s.is_empty()
		&& !is_reserved(s)
		&& s.chars().next().map(is_identifier_start).unwrap_or(false)
		&& s.chars().all(is_identifier_part)
}

/// The generator behind `--deobf`. Indices are global per kind, exactly as in
/// jadx's `DeobfAliasProvider`, so a rename list is reproducible when classes are
/// visited in the same order.
#[derive(Debug, Clone)]
pub struct Deobf {
	pub pkg_index: u32,
	pub cls_index: u32,
	pub fld_index: u32,
	pub mth_index: u32,
	/// jadx: `deobfMaxLength`
	pub max_length: usize,
	/// jadx: `deobfMinLen` -- names at least this long are left alone
	pub min_len: usize,
	/// jadx: `deobfWhitelist` (fully qualified class names to force-rename)
	pub whitelist: Vec<String>,
	/// packages never renamed; the FFI equivalent of jadx's
	/// `deobfSkipPackages` command line option (not a `JadxArgs` field)
	pub skip_packages: Vec<String>,
}

impl Default for Deobf {
	fn default() -> Self {
		// defaults mirror `Args::default()`, i.e. jadx's `JadxArgs`: deobfuscation
		// is off, so no length is "too long" and no name is "too short"
		Deobf {
			pkg_index: 0,
			cls_index: 0,
			fld_index: 0,
			mth_index: 0,
			max_length: usize::MAX,
			min_len: 0,
			whitelist: Vec::new(),
			skip_packages: Vec::new(),
		}
	}
}

impl Deobf {
	pub fn new() -> Deobf {
		Deobf::default()
	}

	pub fn from_args(args: &crate::args::Args) -> Deobf {
		let mut d = Deobf::default();
		d.max_length = args.deobfuscation_max_length;
		d.min_len = args.deobfuscation_min_length;
		d.whitelist = args.deobfuscation_whitelist.clone();
		d
	}

	/// jadx: `DeobfAliasProvider.prepareNamePart`
	pub fn prepare_name_part(&self, name: &str) -> String {
		if name.chars().count() > self.max_length {
			// `Integer.toHexString` prints the unsigned 32 bit value
			format!("x{:x}", java_hash_code(name) as u32)
		} else {
			remove_invalid_chars_middle(name)
		}
	}

	/// jadx: `forPackage`
	pub fn package_alias(&mut self, pkg_name: &str) -> String {
		let out = format!("p{:03}{}", self.pkg_index, self.prepare_name_part(pkg_name));
		self.pkg_index += 1;
		out
	}

	/// jadx: `forClass` + `makeClsPrefix`.
	///
	/// `flags` are the class access flags; the prefix mirrors the superclass chain
	/// only as far as "interface/abstract" goes, because jadx's `getBaseName`
	/// walks `RootNode` for a non-obfuscated ancestor and that model is not part
	/// of this port's rename pipeline.
	pub fn class_alias(&mut self, name: &str, flags: u32) -> String {
		let mut prefix = String::new();
		if access_flags::has(flags, access_flags::flag::ENUM) {
			prefix.push_str("Enum");
		} else if access_flags::has(flags, access_flags::flag::INTERFACE) {
			prefix.push_str("Interface");
		} else if access_flags::has(flags, access_flags::flag::ABSTRACT) {
			prefix.push_str("Abstract");
		}
		let out = format!("{}C{:04}{}", prefix, self.cls_index, self.prepare_name_part(name));
		self.cls_index += 1;
		out
	}

	/// jadx: `forField`
	pub fn field_alias(&mut self, name: &str) -> String {
		let out = format!("f{}{}", self.fld_index, self.prepare_name_part(name));
		self.fld_index += 1;
		out
	}

	/// jadx: `forMethod`; `overridden` selects the `mo` prefix jadx uses when the
	/// method participates in a method-override group.
	pub fn method_alias(&mut self, name: &str, overridden: bool) -> String {
		let prefix = if overridden { "mo" } else { "m" };
		let out = format!("{}{}{}", prefix, self.mth_index, self.prepare_name_part(name));
		self.mth_index += 1;
		out
	}

	/// jadx: the rename conditions -- a name shorter than `deobfMinLen` (or listed
	/// in the whitelist) is worth renaming; `<init>`/`<clinit>` and `Enum`
	/// boilerplate never are.
	pub fn should_rename(&self, name: &str) -> bool {
		if name.starts_with('<') || name == "this" || name == "super" {
			return false;
		}
		if !self.whitelist.is_empty() {
			return true;
		}
		name.chars().count() < self.min_len
	}

	pub fn skip_package(&self, pkg: &str) -> bool {
		self.skip_packages.iter().any(|s| pkg == s || pkg.starts_with(&format!("{}.", s)))
	}
}

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn java_hash_code_matches_the_jvm() {
		// reference values of java.lang.String.hashCode
		assert_eq!(java_hash_code(""), 0);
		assert_eq!(java_hash_code("a"), 97);
		assert_eq!(java_hash_code("ab"), 97 * 31 + 98);
		assert_eq!(java_hash_code("hello"), 99162322);
		assert_eq!(java_hash_code("Hello World"), -862_545_276);
		// overflows must wrap like the JVM does, so the value equals the same
		// recurrence written out with wrapping arithmetic
		let mut h = 0i32;
		for _ in 0..40 {
			h = h.wrapping_mul(31).wrapping_add(97);
		}
		assert_eq!(java_hash_code(&"a".repeat(40)), h);
		// a supplementary-plane char counts as two UTF-16 code units
		assert_eq!(java_hash_code("\u{1F600}"), (0xD83D as i32).wrapping_mul(31).wrapping_add(0xDE00));
	}

	#[test]
	fn identifiers_follow_the_java_rules() {
		assert!(is_valid_identifier("Foo_bar$1"));
		assert!(!is_valid_identifier("1Foo"));
		assert!(!is_valid_identifier("class"));
		assert!(!is_valid_identifier(""));
		assert!(!is_reserved("goto"));
		assert!(is_reserved("goto"));
	}

	#[test]
	fn aliases_follow_jadx_formats() {
		let mut d = Deobf::new();
		assert_eq!(d.package_alias("a"), "p000a");
		assert_eq!(d.class_alias("b", access_flags::flag::INTERFACE), "InterfaceC0000b");
		assert_eq!(d.class_alias("c", 0x4000), "EnumC0001c");
		assert_eq!(d.class_alias("d", access_flags::flag::ABSTRACT), "AbstractC0002d");
		assert_eq!(d.field_alias("a"), "f0a");
		assert_eq!(d.method_alias("a", false), "m0a");
		assert_eq!(d.method_alias("a", true), "mo1a");
	}

	#[test]
	fn long_names_are_hashed_like_jadx() {
		let mut d = Deobf::new();
		d.max_length = 12; // jadx's example config; the default is unbounded
		let long = "aVeryLongObfuscatedName";
		let got = d.prepare_name_part(long);
		assert_eq!(got, format!("x{:x}", java_hash_code(long) as u32));
		assert_eq!(d.prepare_name_part("short"), "short");
	}

	#[test]
	fn constructor_names_are_never_renamed() {
		let mut d = Deobf::new();
		d.min_len = 3;
		assert!(!d.should_rename("<init>"));
		assert!(d.should_rename("a"));
		assert!(!d.should_rename("someNormalName"));
		// with the defaults nothing is short enough to rename
		assert!(!Deobf::new().should_rename("a"));
	}
}
